### ISSUE TITLE
pkg-resources error in requirements.txt

### ISSUE THREAD

**Issue by tomwrobel** [osc-cam/orpheus#1]
The requirements.txt file contains an invalid requirement: pkg-resources==0.0.0

This causes `pip3 install -r requirements.txt` to fail. The line does not seem to be required.

I suspect it's related to this issue: https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by afs25** [comment]
Thank you for reporting this issue @tomwrobel. This was indeed caused by that bug. If you find any other issues with Orpheus, please let me know. The documentation is still very poor, but this is at least in part because I don't want to invest much time documenting a product that nobody intends to use. I should also mention that the current requirements.txt file is minimal and lists only those packages that are needed to get the database running. The parsers contained in the "connectors" folder require some additional packages to run.

**Comment by tomwrobel** [comment]
Hi @afs25! Many thanks for the change, I’ve got an ansible build for Orpheus going now. 

We’re having a long look at Orpheus here at Oxford, although we won’t be deploying anything for a while until ORA4 goes live. Any further documentation you have would be amazing (particularly on how to import data sources), and I’d love the chance to talk to you about it sometime. 

Again, many thanks

**Comment by afs25** [comment]
Good to hear your installation worked @tomwrobel! I will soon document the process of bulk populating the database. It's helpful to know what would be most helpful to document first, so thanks for the suggestion. I am off next week for a family holiday, but if you would like to arrange a call with me sometime after that, just let me know. My e-mail address is afs25 at cam dot ac dot uk.
